### ISSUE TITLE
카메라의 위치 변환.

### ISSUE THREAD

**Issue by BillyoDev** [LBSTECH/naver_map_plugin#10]
변수 선언.
`// naver map.
  List<Marker> _markers = [];
  Completer<NaverMapController> _controller = Completer();

  void _onMapCreated(NaverMapController controller) {
    _controller.complete(controller);
    controller.moveCamera(CameraUpdate.scrollTo(_latLng));
  }`

  // 지도 초기 위치.
`LatLng _latLng = LatLng(37.497620, 127.027341);`

Scaffold body.
`return NaverMap(
      markers: _markers,
      onMapCreated: _onMapCreated,
      initLocationTrackingMode: LocationTrackingMode.NoFollow,
      liteModeEnable: true,
      initialCameraPosition: CameraPosition(
        zoom: 11.0,
        target: _latLng,
      ),
    );`

위치 lat, lng 값 변환.
`setState(() {
 _latLng = LatLng(10.0,10.0);
});`

_onMapCreated 선언한뒤 _latLng 값을 변환 시켜도 지도의 카메라가 이동을 하지 않습니다....
다른 방법이 있을까요?

**Comment by sjpark-lbstech** [comment]
내부 실행에 대한 순서를 짚어드리면 `onMapCreated`되고 나서 네이티브단에 전달된 `initialCameraPosition`으로 이동하게 됩니다. 이 과정에서 맵 타일을 네트워크를 통해 받아와서 이동이 완료되기 이전에는 moveCamera가 동작하지 않습니다.

즉, 지도 객체는 생성되었지만, 초기위치로의 이동이 끝나기 이전에 새로운 위치로의 이동을 하려하기에 동작이 되지 않는 현상입니다. 초기 위치이동이 완료되기 이전에 새로운 위치로 가야한다면 그 위치를 초기 위치로 잡아야합니다.

>  일반적으로 초기위치 이동 완료이후 특정 이벤트에 대한 반응으로 지도를 움직이는게 올바른 사용입니다.

**Comment by BillyoDev** [comment]
저는 초기 카메라 위치를 변수에 선안한 값으로 지정했습니다. 
그 후에 새로운 LatLng 값이 들어오면 변수에 setstate로 다시 선언을 했습니다.
하지만 카메라에 위치는 변경 되지 않았습니다

**Comment by sjpark-lbstech** [comment]
전체코드를 첨부 해주세요. 
현재로서는 실행과정을 파악할 수 없습니다

**Comment by BillyoDev** [comment]
class SearchResultPage extends StatefulWidget {
    
        final SearchModel searchModel;

     const SearchResultPage({Key key, @required this.searchModel})
      : super(key: key);

      @override
    _SearchResultPageState createState() => _SearchResultPageState();
    }

    class _SearchResultPageState extends State<SearchResultPage> {
      GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

      // searchModel.
      SearchModel _searchModel;

      // bloc.
      SearchBloc _searchBloc;

      // device size.
      Size _size;
      double _safeAreaTopHeight;

      // naver map.
      List<Marker> _markers = [];
      Completer<NaverMapController> _controller = Completer();

      void _onMapCreated(NaverMapController controller) {
        _controller.complete(controller);
        controller.moveCamera(CameraUpdate.scrollTo(_latLng));
      }

      // 지도 초기 위치.
      LatLng _latLng = LatLng(37.497620, 127.027341);
  
      void initState() {
        _searchBloc = BlocProvider.of<SearchBloc>(context);

    // 검색 페이지로부터 받아온 모델 동기화.
    setState(() {
      _searchModel = widget.searchModel;
      _latLng = LatLng(widget.searchModel.latLng.latitude,
          widget.searchModel.latLng.longitude);
    });

    super.initState();
      }

      @override
      Widget build(BuildContext context) {
        _safeAreaTopHeight = MediaQuery.of(context).padding.top;
        if (_size == null) {
          setState(() {
            _size = MediaQuery.of(context).size;
          });
        }

        return BlocListener(
          cubit: _searchBloc,
          listener: (context, state) {
            if (state is SearchSuccess) {
              _markers.clear();

              // 네이버 지도 마커 생성.
              WidgetsBinding.instance.addPostFrameCallback((_) {
                OverlayImage.fromAssetImage(
                        ImageConfiguration(), 'assets/location_icon_36_px.webp')
                    .then((image) {
                  setState(() {
                    for (dynamic searchResult in state.placeList) {
                      _markers.add(
                        Marker(
                          captionPerspectiveEnabled: true,
                          icon: image,
                          markerId: searchResult.place_id.toString(),
                          position: LatLng(searchResult.place_information.latitude,
                              searchResult.place_information.longitude),
                          captionText: searchResult.name,
                          captionTextSize: 13,
                          captionColor: kBlackTextColor,
                          width: 36,
                          height: 36,
                          infoWindow: searchResult.name,
                        ),
                      );
                    }
                  });
                });
              });
            }

            // 결과값이 없는 상태.
            else if (state is SearchNoResult) {
              _markers.clear();
              showModalBottomSheet(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                context: context,
                isDismissible: false,
                isScrollControlled: false,
                builder: (context) => _noResultText(context),
              );    
            }
          },
          child: Scaffold(
            key: _scaffoldKey,
            floatingActionButton: _floatingActionBtn(),
            body: Stack(
              children: [
                _naverMap(),
                _appBar(),
              ],
            ),
          ),
        );
      }

      Widget _naverMap() {
        return NaverMap(
          markers: _markers,
          onMapCreated: _onMapCreated,
          initLocationTrackingMode: LocationTrackingMode.NoFollow,
          liteModeEnable: true,
          initialCameraPosition: CameraPosition(
            zoom: 11.0,
            target: _latLng,
          ),
        );
      }

     Widget _appBar() {
        return Container(
          height: !_hasTag ? 54 : 54.0 + 32.0 + 6.0,
          margin: EdgeInsets.only(top: _safeAreaTopHeight + 4),
          decoration: _isScrolledTop
              ? BoxDecoration(
                  color: kWhiteColor,
                  border: Border(
                    bottom: BorderSide(color: kGreyBorderColor, width: 1),
                  ),
                )
              : null,
          child: Column(
            children: [
              Container(
                padding: EdgeInsets.fromLTRB(20, 0, 20, 0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    CupertinoButton(
                      padding: EdgeInsets.zero,
                      onPressed: () {
                        SearchModel _resultFilterSearchModel =
                            _searchModel.copyWith(
                                minDeposit: 0,
                                minMonthPrice: 0,
                                minPriceTime: 0,
                                maxDeposit: 99999999,
                                maxMonthPrice: 99999999,
                                maxPriceTime: 99999999);

                    Navigator.of(context)
                        .push(
                      PageRouteBuilder(
                        opaque: false,
                        transitionDuration: Duration(milliseconds: 500),
                        reverseTransitionDuration: Duration(milliseconds: 500),
                        pageBuilder: (context, animation, secondaryAnimation) =>
                            SearchFilterList(
                          type: _searchModel.reserveType,
                          searchModel: _resultFilterSearchModel,
                        ),
                        transitionsBuilder:
                            (context, animation, secondaryAnimation, child) {
                          var begin = Offset(0.0, 1.0);
                          var end = Offset.zero;
                          var curve = Curves.ease;
                          var tween = Tween(begin: begin, end: end)
                              .chain(CurveTween(curve: curve));

                          return SlideTransition(
                            position: animation.drive(tween),
                            child: child,
                          );
                        },
                      ),
                    )
                        .then(
                      (result) {
                        if (result != null) {
                          _latLng = result.latLng;                 // result.latLng == 다른 페이지에서 받아온 위치 값입니다. ex)LatLng(123,123);
                          makeTagFromFilter(result);
                          setState(() {
                            _searchModel = result;
                          });

                          _searchBloc.add(
                            (result.reserveType == ReserveType.TIME)
                                ? SearchRequestedByTime(
                                    searchModel: _searchModel)
                                : SearchRequestedByMonth(
                                    searchModel: _searchModel,
                                  ),
                          );
                        }
                      },
                    );
                  },
                  child: Container(
                    width: 48,
                    height: 48,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.all(Radius.circular(5)),
                      border: _isScrolledTop
                          ? null
                          : Border.all(
                              color: const Color(0xffeeeeee), width: 1),
                      color: const Color(0xffffffff),
                    ),
                    child: Container(
                      child: OverflowBox(
                        minWidth: 0.0,
                        minHeight: 0.0,
                        maxWidth: double.infinity,
                        child: Image.asset(
                          'assets/ic_filter.webp',
                          width: 24,
                          height: 24,
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
      }


변수 선언 _latLng (이곳의 위치를 저장합니다.) -> onMapCreated 안과  NaverMap 안에 카메라 포지션값을 _latLng을 넣습니다. -> 
그 후 다른 페이지에서 받아온 LatLng 값을 _latLng 변수에 setState 합니다 .

**Comment by sjpark-lbstech** [comment]
제가 이해한 것이 맞다면 검색페이지에서 검색한 특정위치에 대한 정보를 ```pop()```으로 넘기고, 파라미터로 넘어온 위치로 지도를 움직이려 하는것으로 보입니다.

이전에 작성하신 [이슈글에 대한 답변](https://github.com/LBSTECH/naver_map_plugin/issues/9#issuecomment-726417973)에 작성한 내용을 확인하셨나요?  ```initialCameraPosition``` 으로 넘긴 변수(위의 코드에서의 변수명 : _latLng)를 바꿔도 지도는 움직이지 않습니다.

코드의 실행순서가 전혀 올바르지 않습니다. 

- 우선 ```onMapCreated()```에서 

``` dart
void _onMapCreated(NaverMapController controller) {
  _controller.complete(controller);
  // controller.moveCamera(CameraUpdate.scrollTo(_latLng)); // remove this line
}
```


- 이후 검색 페이지에서 결과받아오는 부분

``` dart 
(result) async{
    if (result != null) {
        _latLng = result.latLng;
        final controller = await _controller.future;
        controller.moveCamera(CameraUpdate.scrollTo(_latLng)); // move to here.
        makeTagFromFilter(result);
        setState(() {
            _searchModel = result;
        });
        _searchBloc.add(
            (result.reserveType == ReserveType.TIME) 
                ? SearchRequestedByTime(searchModel: _searchModel)
                : SearchRequestedByMonth(searchModel: _searchModel),
        );
}
```
