### ISSUE TITLE
안녕하세요, 네이버맵 plugin 을 고대하고 있는 flutter 개발자입니다.

### ISSUE THREAD

**Issue by JJayLee** [LBSTECH/naver_map_plugin#11]
안녕하세요, 구글맵으로 지도 기반 앱을 개발하고 있는 Flutter 개발자입니다.
국내 지도에 있어서 구글맵이 너무 정보가 부정확해서 네이버맵을 만드려고 하고 있었는데 마침 이 plugin을 발견해서 정말 기적이라고 생각했습니다. 
아직 베타(?) 버전이신 것 같긴 하지만, 저희 앱에 필요한 기능만 있으면 언제든지라도 바로 이용해보고 싶은 마음입니다ㅜㅜ 
polygon overlay도 추가하실 계획이 있으실까요? 
있으시다면 기분좋게 대기할 수 있고, 없으시다면 contribute하는 형태로라도 만들어봐도 괜찮을 것 같다는 생각인데, 
혹시나해서 적어봅니다. 
naver map plugin을 기다리고 있는 개발자로서 늘 응원합니다. 감사합니다!

**Comment by sjpark-lbstech** [comment]
관심 가져주셔서 감사합니다. 그리고 아시겠지만 아직 베타 버전입니다. 저희 내부 서비스에서 필요한 기능들을 우선적으로 만들어서 사용했습니다. 

확실한 건 polygon은 빠른 시일 내에 추가할 계획이 있지만 정확한 계획은 단언할 수 없습니다.
아무래도 개인 스케줄이 있다보니...
contribute 제안은 감사합니다만 베타 이후에 고려할 내용이라 생각합니다.
