### ISSUE TITLE
Could not find 'libnavermap.so'

### ISSUE THREAD

**Issue by manwooo** [LBSTECH/naver_map_plugin#12]
샘플코드가 얼마전까지 동작했는데 갑자기 동작이 안되네요.

아래 에러 코드를 첨부합니다.
Caused by: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libnavermap.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

이것과 관련이 있는거 같은데.. 왜 갑자기 이럴까요? 

E/flutter (25075): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.ExceptionInInitializerError
E/flutter (25075): 	at com.naver.maps.map.MapView.a(SourceFile:132)
E/flutter (25075): 	at com.naver.maps.map.MapView.<init>(SourceFile:113)
E/flutter (25075): 	at map.naver.plugin.net.lbstech.naver_map_plugin.NaverMapController.<init>(NaverMapController.java:86)
E/flutter (25075): 	at map.naver.plugin.net.lbstech.naver_map_plugin.NaverMapBuilder.build(NaverMapBuilder.java:41)
E/flutter (25075): 	at map.naver.plugin.net.lbstech.naver_map_plugin.NaverMapFactory.create(NaverMapFactory.java:58)
E/flutter (25075): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/flutter (25075): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
E/flutter (25075): 	at android.app.Dialog.show(Dialog.java:424)
E/flutter (25075): 	at android.app.Presentation.show(Presentation.java:283)
E/flutter (25075): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter (25075): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter (25075): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/flutter (25075): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (25075): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (25075): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (25075): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (25075): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (25075): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25075): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (25075): 	at android.os.Looper.loop(Looper.java:197)
E/flutter (25075): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/flutter (25075): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25075): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/flutter (25075): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/flutter (25075): Caused by: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libnavermap.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
E/flutter (25075): 	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
E/flutter (25075): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
E/flutter (25075): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
E/flutter (25075): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
E/flutter (25075): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
E/flutter (25075): 	at com.naver.maps.map.internal.d.a(SourceFile:47)
E/flutter (25075): 	at com.naver.maps.map.renderer.MapRenderer.<clinit>(SourceFile:30)
E/flutter (25075): 	... 24 more
E/flutter (25075): 
F/flutter (25075): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
F/libc    (25075): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25075 (utter_naver_app), pid 25075 (utter_naver_app)

**Comment by manwooo** [comment]
아... 원인을 알았습니다. 

안드로이드 쪽에 gradle 빌드 설정을 안해서 그런거였네요.
https://docs.ncloud.com/ko/naveropenapi_v3/maps/android-sdk/v3/start.html

왜 그전에는 설정없이 되었는지 의문이네요?

**Comment by sjpark-lbstech** [comment]
저도 동일한 문제가 발생했었습니다. Build 설정은 플러그인에서 가져가기 때문에 Read me에서 따로 작성하지 않았던 부분이구요. 해당 플러그인을 사용하고 있는 서비스의 지도가 갑자기 작동하지 않는 문제가 발생했고 확인해보니 appbundle 에 so 파일이 누락이 되있었습니다. 

> 해결책은 간단했습니다. ```flutter clean``` 하고 다시 빌드하니 리소스가 정상적으로 들어가더군요.

아마 아직 flutter engine이 완벽히 안정적이지는 않아서 발생하는 문제인 듯 보입니다. (정확하지는 않지만 플러그인의 Gradle의 리소스 누락이 발생하는 듯한 느낌입니다. ) 루트 프로젝트에 종속성을 선언하는 것도 하나의 방법인 듯 합니다.
 
저도 한참을 찾다 ```flutter clean```에 허탈함을 느꼈습니다..
