### ISSUE TITLE
주소 검색

### ISSUE THREAD

**Issue by DaeHyeonNam** [LBSTECH/naver_map_plugin#13]
안녕하세요! 좋은 플러그인 공유해주셔서 감사합니다.
혹시 주소를 통해 검색할 수 있는 기능을 업데이트하실 계획이 있으신가요?

**Comment by DaeHyeonNam** [comment]
아하 geocoding은 restapi 밖에 지원하지 않는 것을 보니 이건 제가 직접 call을 보내고 결과랑 위도,경도를 가져와서 지도를 움직이는 방법 밖에 없는건가요?

**Comment by sjpark-lbstech** [comment]
네 맞습니다. 주소 검색은 추가적으로 구현하셔야하는 부분이에요
