### ISSUE TITLE
Customizing location button

### ISSUE THREAD

**Issue by DaeHyeonNam** [LBSTECH/naver_map_plugin#14]
안녕하세요! 
혹시 현위치 버튼 위치, 색, 크기등을 커스터 마이즈 할 수 있는 방법이 있을까요?
감사합니다 :) 새해 복 많이 받으세요!

**Comment by sjpark-lbstech** [comment]
네이버 지도 API에서는 해당기능을 제공하지 않습니다.

다른 모양의 컨트롤러는 별도로 구현해야 합니다. 현재 네이버 api에서 제공하는 컨트롤러들은 ```NaverMapController``` 의 method들로 모두 구현가능합니다.

**Comment by DaeHyeonNam** [comment]
흠.. 그런데 별도로 제가 버튼을 디자인해서 만들고 싶다면, 현재 사용자의 위치정보를 가져오는 method가 있어야 할 것 같은데 이 naver map plugin에서는 이 method를 제공하지 않죠.? 다른 플러그인을 사용해 구현해야 하나요?

**Comment by sjpark-lbstech** [comment]
네 플렛폼 채널이나 다른 플러그인등 방밥은 많습니다.
현위치만 하시는거면 ```NaverMapController```의 ```setLocationTrackingMode()```를 사용하면 됩니다.
