### ISSUE TITLE
rebuilding when phone direction changes

### ISSUE THREAD

**Issue by DaeHyeonNam** [LBSTECH/naver_map_plugin#15]
안녕하세요! 디바이스의 방향이 바뀌면  widget의 build다시 불리게 되는데, 이때 naver map이 다시 초기화가 되네요.
혹시 이 초기화를 막을 수 있는 방법이 있을까요?

**Comment by sjpark-lbstech** [comment]
디바이스의 방향이 바뀐다는 말이 가로, 세로 자세가 바뀐다는걸 의미하시는거면 플러그인 자체에서는 없습니다

**Comment by DaeHyeonNam** [comment]
감사합니다 !
