### ISSUE TITLE
onCameraChange Error

### ISSUE THREAD

**Issue by Taeil-Yun** [LBSTECH/naver_map_plugin#16]
안녕하세요! 플러그인 잘 사용하고있습니다.

저는 얼마전까지 0.9.0 버전을 사용했었습니다. 그 때 까지만해도 문제가 없었습니다. 하지만 새로운 0.9.1 버전이 나온것을 확인하고 적용 후에 pub get을 한 후부터 onCameraChange부분 Code Error가 나기 시작했습니다. 저는 이유를 찾다가 0.9.0 버전에도 0.9.1 버전이 적용된것을 확인했습니다.

혹시라도 0.9.0 버전에도 0.9.1 버전을 실수로 적용 하셨을수도있으실까봐 이슈남겨드립니다.

**Comment by sjpark-lbstech** [comment]
현재 사용중인 pudspec.yaml 문서에서 dependency 선언한 부분 한번 확인해주세요.
혹시 ```^0.9.0``` 이라고 되어있지는 않나요? 
pub.dev에 한번 publish 한걸 변경할 수는 없어서 0.9.0버전의 코드가 바뀌지는 않았을겁니다.
