### ISSUE TITLE
Cannot decode bitmap when is change icon 

### ISSUE THREAD

**Issue by idevbao** [LBSTECH/naver_map_plugin#18]
I/flutter (10433): Instance of 'OverlayImage'
153
E/NaverMap(10433): Cannot decode bitmap

my code:

    // OverlayImage.fromAssetImage(
    //   ImageConfiguration(),
    //   'icons/ic_marker.png',
    // ).then((image) {
    //   print(image);
    //   _markers.add(Marker(
    //       markerId: DateTime.now().toIso8601String(),
    //       position: position,
    //       icon: image,
    //       captionText: "커스텀 아이콘",
    //       captionColor: Colors.indigo,
    //       onMarkerTab: _onMarkerTap));
    // });

**Comment by sjpark-lbstech** [comment]
please leave the platform

**Comment by sjpark-lbstech** [comment]
Leave the more information about the error.

- run ```flutter pub upgrade naver_map_plugin``` cuz that looks like old version.
- ```OverlayImage``` has to be made after the ```build()```

**Comment by idevbao** [comment]
tks
