### ISSUE TITLE
maker caption 설정

### ISSUE THREAD

**Issue by BillyoDev** [LBSTECH/naver_map_plugin#19]
여러개의 마커가 존재하고, 마커를 클릭을 할때 caption의 text가 보여지고 있습니다.
그런데 caption의 text가 다른 마커의 가려져서 안보이는 현상이 있는데, 
caption의 text를 항상 화면 제일 위에 위치해서 가려지는 현상을 방지는 하는 방법이 있을까요?
<img width="116" alt="무제" src="https://user-images.githubusercontent.com/71685621/107304638-d5523180-6ac4-11eb-8287-c9bb681c8e22.png">

**Comment by BillyoDev** [comment]
> 여러개의 마커가 존재하고, 마커를 클릭을 할때 caption의 text가 보여지고 있습니다.
> 그런데 caption의 text가 다른 마커의 가려져서 안보이는 현상이 있는데,
> caption의 text를 항상 화면 제일 위에 위치해서 가려지는 현상을 방지는 하는 방법이 있을까요?
> <img alt="무제" width="116" src="https://user-images.githubusercontent.com/71685621/107304638-d5523180-6ac4-11eb-8287-c9bb681c8e22.png">

**Comment by BillyoDev** [comment]
> 여러개의 마커가 존재하고, 마커를 클릭을 할때 caption의 text가 보여지고 있습니다.
> 그런데 caption의 text가 다른 마커의 가려져서 안보이는 현상이 있는데,
> caption의 text를 항상 화면 제일 위에 위치해서 가려지는 현상을 방지는 하는 방법이 있을까요?
> <img alt="무제" width="116" src="https://user-images.githubusercontent.com/71685621/107304638-d5523180-6ac4-11eb-8287-c9bb681c8e22.png">

**Comment by sjpark-lbstech** [comment]
마커 속성에 보면 zIndex 가 있습니다. 상단에 놓고 싶은 마커의 zIndex를 가장 큰 값으로 설정하면 마커와 caption text가 다른 요소에 의해 가려지지 않습니다.
