### ISSUE TITLE
issue with pom file

### ISSUE THREAD

**Issue by kar1981** [LBSTECH/naver_map_plugin#20]
I've added naver_map_plugin: ^0.9.3 to pubspec.yaml, but when going to build, the below error occurred. Following that pom link via browser also gives a 403.

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':naver_map_plugin:generateDebugRFile'.
> > Could not resolve all files for configuration ':naver_map_plugin:debugCompileClasspath'.
>    > Could not resolve com.naver.maps:map-sdk:3.9.1.
>      Required by:
>          project :naver_map_plugin
>       > Could not resolve com.naver.maps:map-sdk:3.9.1.
>          > Could not get resource 'https://navercorp.bintray.com/maps/com/naver/maps/map-sdk/3.9.1/map-sdk-3.9.1.pom'.
>             > Could not HEAD 'https://navercorp.bintray.com/maps/com/naver/maps/map-sdk/3.9.1/map-sdk-3.9.1.pom'. Received status code 403 from server: Forbidden
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 12s
> Exception: Gradle task assembleDebug failed with exit code 1

**Comment by gracegyu** [comment]
I have the same problem.

**Comment by sjpark-lbstech** [comment]
naver SDK's maven repository url was changed. please edit gradle file directly.

> ROOT/android/build.gradle

``` groovy
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://naver.jfrog.io/artifactory/maven/'
        }
    }
}
```

that'll be fixed soon. i can say that

**Comment by kar1981** [comment]
Thanks! that works now

**Comment by DJSeokHo** [comment]
url 'https://naver.jfrog.io/artifactory/maven/' works for me
