### ISSUE TITLE
Android Emulator에서는 지도를 출력하려고 할때 crash가 납니다.

### ISSUE THREAD

**Issue by gracegyu** [LBSTECH/naver_map_plugin#21]
pubspec.yaml 에 naver_map_plugin: ^0.9.3를 적용해서 수행해 본 결과 iOS Simulator에서는 지도가 아주 잘 표시됩니다.
그런데, Android Emulator에서는 아래 Error와 함께 Crash가 납니다. 
Emulator는 Pixel 2 API 30 (Android 11.0)을 사용했습니다.
어떻게 하면 Crash가 안나고 Emulator에서 시도해 볼 수 있을까요?

`
W/Gralloc4( 7099): allocator 3.x is not supported
W/atech.cleverpa( 7099): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
W/atech.cleverpa( 7099): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
W/atech.cleverpa( 7099): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
I/TetheringManager( 7099): registerTetheringEventCallback:com.vatech.cleverpam
D/TransportRuntime.SQLiteEventStore( 7099): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
`

**Comment by gracegyu** [comment]
Android Real Device에서도 Crash가 납니다.
모델은 ESAT-21 Galaxy Tab A (2017) 입니다.


`
D/Dialog  (29607): mIsSamsungBasicInteraction = false
D/Dialog  (29607): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
W/atech.cleverpa(29607): Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
W/atech.cleverpa(29607): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
W/atech.cleverpa(29607): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
W/atech.cleverpa(29607): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
I/DecorView(29607): mWindow.mActivityCurrentConfig is null.
I/MultiWindowDecorSupport(29607): updateCaptionType >> DecorView@e758396[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/MultiWindowDecorSupport(29607): setCaptionType = 0, DecorView = DecorView@e758396[]
D/InputTransport(29607): Input channel constructed: fd=137
D/ViewRootImpl@90c1370[MainActivity](29607): setView = DecorView@e758396[MainActivity] TM=true MM=false
W/System  (29607): A resource failed to call release. 
`

**Comment by sjpark-lbstech** [comment]
말씀해주신 에뮬레이터의 환경을 구성해서 돌려보았을때 에러없이 잘 동작합니다..
실기기는 말씀해주신 모델은 없어서 테스트 해보지는 못했어요.
혹시 ```flutter clean``` 하시고 샘플코드를 돌려도 동일한 현상이 발생하는지 확인 한번 부탁 드립니다.

**Comment by sjpark-lbstech** [comment]
답변이 없어서 우선 닫습니다.

**Comment by gracegyu** [comment]
flutter clean도 해보고 샘플코드를 돌려봐도 똑같이 Crash가 발생합니다. Crash 발생 시 아래 에러가 찍힙니다.

allocator 3.x is not supported

**Comment by sjpark-lbstech** [comment]
```flutter doctor``` 한번만 남겨주세요

**Comment by gracegyu** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio
[✓] VS Code (version 1.53.2)
[✓] Connected device (4 available)
    ! Error: Raymond’s iPhone11 is busy: Preparing Raymond’s iPhone11 for development. Xcode will continue when Raymond’s iPhone11 is finished. (code -10)

**Comment by gracegyu** [comment]
Android toolchain 문제는 아래 처럼 해결했습니다. 여전히 allocator 3.x is not supported 에러가 발생하면 Crash납니다. 

[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio
[✓] VS Code (version 1.54.1)
[✓] Connected device (3 available)

**Comment by ktw1318** [comment]
동일한 문제가 있는데 본건 어떻게 해결 하나요?

**Comment by gracegyu** [comment]
전, 아직 해결 못했습니다.

**Comment by ktw1318** [comment]
삼성폰은 끝임없이 아래 에러가 
E/DecorView(28977): mWindow.mActivityCurrentConfig is null

LG폰은 아래 에러가 계속 뜨네요
E/LocationManager(19267): [LGE_GNSS] GnssStatusListenerTransport onNmeaReceived timestamp=1623399071703 

해결방법이 없을가요 ㅠ
