### ISSUE TITLE
Marker properties are set to final

### ISSUE THREAD

**Issue by kar1981** [LBSTECH/naver_map_plugin#22]
Is there a way to change the properties of a marker after it has been created?
For example, in the "onMarkerTab" set the colour of the marker to a different colour. At the moment all the properties of a marker are Final so nothing can be dynamically changed.

Thank you!

**Comment by sjpark-lbstech** [comment]
if there are blue markers(default color) and you wanna change marker's color to red by tapping, you should replace selected marker with new marker instance has red color property. and have to call ```setState()```

**Comment by kar1981** [comment]
I see. it is not easy to replace the marker that was tapped because the marker is a list and not a map, so I needed to keep a separate map of <marker_id, index> where index is the position of the marker in the list so when I replace the marker, I can know which index of the marker to replace.

I think for interactivity with markers, ideally the markers are:
1. added to a map<id,marker> rather than a list<marker>
2. allowing the attributes of the markers be changed dynamically (such as colour, size, z-index etc..). 
Just curious, was there a reason why every attribute is locked to final?

BTW, **thanks for creating this widget**, it works really well!

**Comment by sjpark-lbstech** [comment]
below is the part of sample code using marker with tap event. 
Yes... as you said, that looks like unreasonable.

``` dart
class MarkerMapPage extends StatefulWidget {
  @override
  _MarkerMapPageState createState() => _MarkerMapPageState();
}

class _MarkerMapPageState extends State<MarkerMapPage> {
    List<Marker> _markers = [];

  @override
  void initState() {
    // initialization marker list
    _markers.add(Marker(
      markerId: 'id',
      position: LatLng(37.563600, 126.962370),
      captionText: "custom icon",
      iconTintColor: Colors.indigo,  // default color is indigo
      onMarkerTab: _onMarkerTap
    ));
  }

    @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: NaverMap(
            onMapCreated: _onMapCreated,
            onMapTap: _onMapTap,
            markers: _markers,
            initLocationTrackingMode: LocationTrackingMode.Follow,
          ),
      ),
    );
  }

  void _onMarkerTap(Marker marker, Map<String, int> iconSize) {
   final selectedMarkerIndex = _markers.indexWhere((prev) => prev.markerId == marker.markerId);
    if (mounted) setState(() => _markers[selectedMarkerIndex] = Marker(
        markerId: marker.markerId,
        position: marker.position,
        onMarkerTab: _onMarkerTap,
        captionText: "custom icon",  
        iconTintColor: Colors.red  // change color 
    ));
  }

}
```

thanks to opinion. and that was worth considering. i think you're right. 
so, I'll allow the attributes of the markers be changed dynamically.
When I first made this plug in, i benchmarked Google map plug-in. and I didn't consider about this situation... :(

these days.. sadly, i'm too busy to update version...
please wait for the better version.

thank you for your interest. and sorry for lazy update.

**Comment by kar1981** [comment]
thanks for being responsive and I think everyone here appreciates your work. Will look forward to the new version updates:)
