### ISSUE TITLE
libnavermap.so 파일을 찾을수 없습니다.

### ISSUE THREAD

**Issue by manwooo** [LBSTECH/naver_map_plugin#23]
안녕하세요. 
정확히 기억은 안나지만 한달전까지는 잘쓰고 있었는데 버전이 업데이트가 되어서 실행을 해보았는데 
맵로드하다가 계속 죽어서.
샘플 코드를 실행을 해보았는데 아래와 같이 오류가 나면서 종료가 되는데 혹시 조치할 사항이 따로 있는지 알수 있을까요?

아래 메시지를 보니 .so 파일이 필요한듯한데
아래 에러 메시지로 보면 지원되는 ABI가 3가지 인듯합니다.
겔럭시 노트 9에서 테스트 중이고, ABI: 'arm64' 이것때문에 그런문제가 발생하는것 같은데 arm64 ABI로 어떻게 사용할 수 있나요?

E/flutter (17352): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.ExceptionInInitializerError
E/flutter (17352): 	at com.naver.maps.map.MapView.a(SourceFile:133)
E/flutter (17352): 	at com.naver.maps.map.MapView.<init>(SourceFile:113)
E/flutter (17352): 	at map.naver.plugin.net.lbstech.naver_map_plugin.NaverMapController.<init>(NaverMapController.java:88)
E/flutter (17352): 	at map.naver.plugin.net.lbstech.naver_map_plugin.NaverMapBuilder.build(NaverMapBuilder.java:46)
E/flutter (17352): 	at map.naver.plugin.net.lbstech.naver_map_plugin.NaverMapFactory.create(NaverMapFactory.java:62)
E/flutter (17352): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/flutter (17352): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
E/flutter (17352): 	at android.app.Dialog.show(Dialog.java:424)
E/flutter (17352): 	at android.app.Presentation.show(Presentation.java:290)
................................

E/flutter (27968): Caused by: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libnavermap.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

**Comment by manwooo** [comment]
원인을 알았습니다. 
\build\app\outputs\flutter-apk\
여기에 보면 app.apk를 설치하는데 app.apk에는 so가 있는 lib 폴더가 없습니다. 
app-debug.apk에도 없고 app-release.apk에는 존재합니다.

임시방편으로 app-release.apk를 설치하고 안드로이드 스튜디오에서 run을 하니 지도가 나옵니다.

apk를 빌드하는 flutter의 문제인걸까요... 이상한 증상이네요.

**Comment by sjpark-lbstech** [comment]
저도 동일한 경우가 많았었는데
```flutter clean``` 하고 다시 build 하면 들어가더라구요
정확한 이유는 모르겠지만 추측컨데 flutter부분에서 불안정하게 발생하는 에러인것 같습니다. 
android studio에서 apk열어보면 naver map의 iso 파일이 없는 경우가 발생할 수 있어서 저같은 경우는 항상 새로운 버전 개시전에 확인하고 배포합니다
