### ISSUE TITLE
안드로이드에서 느린 성능은 Flutter의 한계일까요?

### ISSUE THREAD

**Issue by dev-dimsum** [LBSTECH/naver_map_plugin#27]
안녕하세요, 플러그인 잘 만들어 주셔서 감사합니다. 성능 좋은 안드로이드 스마트폰 (OnePlus 6P) 에서도 랙 걸리고 성능이 느리던데 이건 Flutter의 한계일까요?

GLsurfaceView가 textureView보다 조금 빠른 것 같았지만 둘 다 Kotlin보다 한 5-10배 정도 느린 것 같습니다.

네이버에서 제공하는 안드로이드 Native SDK를 그대로 사용하신거 같은데 혹시 저 말고 이런 부분을 느끼신 분 또 있으신지요.
https://github.com/LBSTECH/naver_map_plugin/blob/master/android/src/main/java/map/naver/plugin/net/lbstech/naver_map_plugin/NaverMapController.java#L106

이렇게 MethodChannel 사용해서 만들면 성능이 Kotlin과 흡사 할 줄 알았는데 약간 의외였습니다.

혹시 제가 도울 수 있는 부분이라도 있는지 아이디어 공유해 주시면 검토해 보겠습니다. 감사합니다.

**Comment by sjpark-lbstech** [comment]
안녕하세요. 우선 Kotlin 보다 느리다는 말이 조금 혼동이 오네요.  조금 더 질문의 요지를 정확히 해주시면 답변을 상세히 해드릴 수 있을것 같아요. 언급하신 문장에서

> ___이렇게 MethodChannel 사용해서 만들면 성능이 Kotlin과 흡사 할 줄 알았는데 약간 의외였습니다.___

데이터만 주고 받는게 아니라 뷰가 변경되고 업데이트 되는 과정입니다. ```PlatformView```의 구조는 그렇게 간단하지 않습니다. 5~10배 정도 느리다고 하는 부분이 어떤 부분인지 언급해주시면 감사하겠습니다.

Flutter view에서 느려보이는 건 Flutter에서 native에서 만든 view를 끌어다오기 때문입니다. 네이티브에서 뷰를 만들어서 Flutter 엔진에서 띄우는 과정이 생각보다 무거워요. 단일 텍스트뷰 하나 끌어가는것도 왠만큼 복잡한 위젯트리보다 훨씬 더 무겁습니다. 현재 platform view 중 퍼포먼스가 향상된 클래스를 시험 중에 있습니다. 처음 빌드하는 과정은 일반 Flutter Widget을 사용하는 것보다 5~10배 정도 시간이 더 걸리는 것이 맞습니다. 네이티브에서도 지도 화면을 만드는게 오래걸리기 때문이죠.

**Comment by dev-dimsum** [comment]
답변 감사합니다! 몰라서 자세히 말 못 드렸는데 조금 더 연구한 후 보고 드리겠습니다.

간단하게는 네이버 맵 SDK 예제와 이 플러그인 예제의 성능을 비교하였습니다.

https://github.com/navermaps/android-map-sdk
vs
https://github.com/LBSTECH/naver_map_plugin

연관 없을 수 있지만 참고로 Flutter animation 엔진을 OpenGL 에서 Metal로 바꾼 후 iOS에서는 문제 있다는데, 제가 한 질문과는 다를 수 있습니다.
https://github.com/flutter/flutter/issues/32170

공교롭게도 Flutter 튜닝하시던 liyuqian이 2월에 이직 하셨네요.
https://medium.com/flutter/flutter-performance-updates-in-the-first-half-of-2020-5c597168b6bb

허나 Google Map SDK Animation 예제는 느리지 않아서 Flutter에 희망을 갖고 다시 도전해 보겠습니다.
https://github.com/atiqsamtia/interactive_maps_marker_flutter

감사합니다 수고하세요!
