### ISSUE TITLE
How to get current zoom?

### ISSUE THREAD

**Issue by nguyenxuankiet262** [LBSTECH/naver_map_plugin#28]
It would be nice to add a feature in NaverMap something like onZoomChanged: (double zoom){} so that we can see what is the zoom value user has selected.

**Comment by sjpark-lbstech** [comment]
if zoom was changed, camera(view port) was changed. you can use ```onCameraIdle``` called when the camera stops moving. 
that callback is void callback with no parameter. so, use ```NaverMapController``` created from ```onMapCreated``` callback's parameter. and you can get camera position by using ```naverMapController.getCameraPosition()```.

**Comment by ktw1318** [comment]
예제가 많지 않아서 여기 코멘트 달아 놓습니다. 많은 분들이 참조 하시면 좋을듯 해서

 void _onCameraIdle()  async{
    // print('카메라 움직임 멈춤');
    final controller = await _controller.future;
    controller.getCameraPosition().then((value) {
      print('==현재 카메라 상태 정보==');
      print(value.zoom);
      print(value.target);
      print(value.tilt);
      print(value.bearing);
    });

  }
