### ISSUE TITLE
Callback for current position

### ISSUE THREAD

**Issue by kar1981** [LBSTECH/naver_map_plugin#29]
Hi!

Is there any way to expose the lat, lng of the user's current position when tracking is turned on (eg: NoFollow)?

I think in the Naver Maps android API, there is a callback for when the user's location changed, could this feature be brought into the Flutter plugin?

The use case is to be able to calculate distance between user's current position with a marker location. It's really good that the plugin currently supports enabling location tracking, but just visually seeing the user's current location is not so useful when we are not able to capture the user's lat, lng at that point. 

example use cases: 
-triggering events based on user's location
-informing users how far a marker is relative to their position
-displaying only certain markers within a set radius of the user's position

This feature will make allow us to make features that is more interactive to the user. Please please please consider it:)

Thanks!

**Comment by sjpark-lbstech** [comment]
you're right. there's callback for current location changes in Android(```NaverMap.OnLocationChangeListener```) . but in iOS, there's no delegate for user's location update. and i should consider about Android and iOS. 
As you said, callback for location changes is a significant feature. so If it goes against equity, developers will need different codes for different platform and complex structure. please understand this situation.. flutter is a cross-platform framework. 

There's so many way to get current GPS such as other plug-in, method channel, event channel. That's opt to you. 
after you get current coordinates, All the examples you mentioned can be implemented. 

Thanks.

**Comment by kar1981** [comment]
I wasn't aware that it was a feature only available in the Naver Map's Android SDK - sorry about that. It makes sense and I agree with your point about the equality and that Flutter is a cross-platform framework - after all, it is a major reason why we are all interested in developing using flutter. 

Thanks for pointing out that there are other options to get the gps coordinates, I will look into those:)

By the way, I saw your note around hybrid composition and it looks pretty powerful. to quote flutter.dev:

> This allows you, for example, to use the native Google Maps from the Android and iOS SDKs directly inside your Flutter app, by using Platform Views.

and also thanks for updating the code for the marker attributes!

**Comment by sjpark-lbstech** [comment]
Thank you for opinion . 

at [___release: v0.9.4___](https://github.com/LBSTECH/naver_map_plugin/releases/tag/0.9.4), i wrote it as below.. 

>I'm considering about using hybrid composition that requires flutter version 1.22.2. so, that will be applied in the future, cuz lots of people use lower version.

so i'm working on it. Thanks for reminding me.
