### ISSUE TITLE
question regarding activeLayers

### ISSUE THREAD

**Issue by kar1981** [LBSTECH/naver_map_plugin#31]
Hi - I have a question regarding selecting which layers to display on the map. I am trying to let the map **not** show places like Starbucks or banks or 7-Elven, etc...

In the plug-in, there is the comments:
> /// 건물레이어를 지우고 싶으면 빈 리스트를 파라미터로 넘겨주세요.

 but I am having trouble getting this to work. When I init the map like this:
```
NaverMap(
      ...
      activeLayers: [],
      ...
);
```
The building layer is still shown.

I also tried:

```
List<MapLayer> _layers = [];

NaverMap(
      ...
      activeLayers: _layers,
      ...
);

```
The building layer is also still shown.

Then I tried to give only one different layer:
```
List<MapLayer> _layers = [];
...
_layers.add(MapLayer.LAYER_GROUP_BICYCLE);
...
NaverMap(
      ...
      activeLayers: _layers,
      ...
);
```
The bicycle layer seems to be showing, but the building layer is also still showing:(

How do I make the building layer disappear? The Naver Map API documentation says that the LAYER_GROUP_BUILDING is enabled by default. But it also says that layer can be turned off by calling: 
`naverMap.setLayerGroupEnabled(NaverMap.LAYER_GROUP_BUILDING, false);`

I think there is a way to do it in your flutter plug-in, but I can't seem to get it working. Can you please help?

Thanks!

**Comment by sjpark-lbstech** [comment]
building layer means polygon line of buildings. 
see the screenshot below.
 
> when building layer inactivated.
<img src = "https://user-images.githubusercontent.com/57393376/110396386-4c261e80-80b3-11eb-9f5a-af8a6db4e0fa.jpg" width="40%">

> when building layer activated.
<img src = "https://user-images.githubusercontent.com/57393376/110396389-4d574b80-80b3-11eb-8538-506d7c9cfb26.jpg" width="40%">

i think you wanna remove symbols on the map tile. but naver map SDK doesn't supported. 
sadly, only satellite type map has no symbols.

**Comment by kar1981** [comment]
actually there is kind of a "way" to do it... 
if the symbolScale: 0, then all the building markers disappear:)

But feels like a ghost map afterwards haha
