### ISSUE TITLE
마커 사라짐 문제

### ISSUE THREAD

**Issue by DaeHyeonNam** [LBSTECH/naver_map_plugin#33]
현재 서울에 마커가 8개 정도 있는데, 지도를 축소를 하다보면 어느 순간 8개 중 1개만 남고 나머지는 다 안보이게 됩니다. 다시 확대를 하면 생겨나구요.
부산에 마커를 생성해서 테스트 해보았더니, 아마 자동으로 어느정도 줌아웃이 되면 그 지역에 소수의 마커들만 남게 되는 것 같습니다. 혹시 이 옵션을 끌 수 있나요?
감사합니다.

**Comment by sjpark-lbstech** [comment]
혹시 마커에 ```minZoom``` 속성이 들어가있나요?
```minZoom```에 값이 있거나, 없는데도 불구하고 동일한 현상이 발생하는 경우 ```minZoom```속성에 1을 전달해주세요

**Comment by DaeHyeonNam** [comment]
![image](https://user-images.githubusercontent.com/40844251/111304746-6bb3dd00-8699-11eb-9143-282c9d3712a7.png)
minZoom이 없는데도 동일한 현상이 있습니다. 1로 해도 마찬가지 이네요.. 현재 버전은 0.9.0 사용하고 있습니다. 
0.9.5는 overlayImage할 때 context를 사용해야하는 문제 때문에 사용하지 못하고 있습니다.

**Comment by sjpark-lbstech** [comment]
상위버전으로 마이그래이션 한번 해보시는걸 추천드립니다. 
제가 @DaeHyeonNam 님의 코드를 돌려볼 수 없어서 정확히 어떤 상황인지 유추하기가 어렵네요.. 

overlayImage를 만드는 부분에서 context 사용하는 예제는 아래와 같습니다.
``` dart
  OverlayImage _myIcon;

  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      OverlayImage.fromAssetImage(
        assetName: 'icon/marker.png',
        context: context,
      ).then((image) {
        if(mounted) setState(() => _myIcon = image);
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: NaverMap(
          onMapCreated: _onMapCreated,
          onMapTap: _onMapTap,
          markers: Marker(
            markerId: 'id',
            position: LatLng(37.563600, 126.962370),
            icon: _myIcon,
          ),
          initLocationTrackingMode: LocationTrackingMode.Follow,
        ),
      ),
    );
  }
```

해당 상황이 일어나는 기종이나, OS version, 스크린샷등 더 자세한 정보가 있으면 저도 동일한 환경에서 진행해보겠습니다

**Comment by ktw1318** [comment]
저는 반대 케이스 인데.. 지도에서 일정 크기가 줌으로 땡겨서 넓게 볼때 마커가 소수만 나오도록 할수 있는 옵션이 있을까요? 아무리  보아도 옵션이 안보이는것 같아서..
