### ISSUE TITLE
네이버 지도 기본 최소 zoom / 최대 zoom 영역 설정은 어떻게 할까요?

### ISSUE THREAD

**Issue by ktw1318** [LBSTECH/naver_map_plugin#43]
기본적으로 지도내 줌인아웃 최소 최대 zoom값을 지정하는 메소드가 안보여서 문의 드립니다.

맵에서 지정된 zoom 최소값과 최대값 maxZoom , minZoom 은 지정 방법 알려주시면 너무 감사하겠습니다.

**Comment by note11g** [comment]
NaverMap의 Constructor에 minZoom과 maxZoom이 있습니다.
해당 변수와 함께 Initialize 해주시면 될 것 같습니다.

또한, default는 네이버 맵 API와 같습니다. (0.0 ~ 21.0)

/// ## 최소 줌 레벨 제한 ##
final double minZoom;

/// ## 최대 줌 레벨 제한 ##
final double maxZoom;
