### ISSUE TITLE
flutter 2.2.3 -> 2.5 버전으로 업그레이드후 샘플 코드 실행에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by webvine** [LBSTECH/naver_map_plugin#47]
안녕하세요.^^; 개발하신 코드를 너무 잘 사용하고 있습니다...

샘플예제를 실행하는데 flutter sdk 2.2.3 에서 잘 동작하는데 2.5 로 업그레이드후 설정 변경 및 실행하면 아래와 같은 에러가 발생합니다..

///////////////////////////
building for iOS Simulator, but linking in dylib built for iOS for architecture arm64

참고 부탁드립니다..^^;

다시한번 감사드립니다...

**Comment by hystericcore** [comment]
혹시나 이후에 찾으시는 분이 있을까 싶어.. 저는 아래와 같은 설정으로 해결하였습니다.
https://stackoverflow.com/a/65451636

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    ## 빌드 설정 추가
    target.build_configurations.each do |config|
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] =  `uname -m`
    end
  end
end
```
