### ISSUE TITLE
[Android] Invalid type casting for setting captionTextSize and subCaptionTextSize in Marker.

### ISSUE THREAD

**Issue by njovy** [LBSTECH/naver_map_plugin#5]
Marker사용 시 captionTextSize, subCaptionTextSize를 설정할 경우 dart와 java간 타입 캐스팅이 제대로 이루어지지 않아 에러가 발생합니다.

[captionTextSize](https://github.com/LBSTECH/naver_map_plugin/blob/master/android/src/main/java/map/naver/plugin/net/lbstech/naver_map_plugin/NaverMarkerController.java#L110-L111) - dart에서 double로 받은 뒤 java에서 float으로 캐스팅 -> 실패 - ClassCastException

[subCaptionTextSize](https://github.com/LBSTECH/naver_map_plugin/blob/master/android/src/main/java/map/naver/plugin/net/lbstech/naver_map_plugin/NaverMarkerController.java#L162-L163) - dart에서 double로 받은뒤 java에서 int로 캐스팅 -> 실패 - ClassCastException

**Comment by sjpark-lbstech** [comment]
코드 수정에 누락이 있던 부분 수정 완료했습니다.

### Marker
아래 3가지 속성에 대한 android Native와의 형변환중 발생하는 에러.
- captionTextSize
- subCaptionTextSize
- alpha

**Comment by njovy** [comment]
@sjpark-lbstech 항상 빠른 피드백 해주셔서 정말 감사드립니다!
