### ISSUE TITLE
[iOS] Unhandled Exception: type 'double' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by DylanMsK** [LBSTECH/naver_map_plugin#6]
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'double' is not a subtype of type 'int'
#0      NaverMapController.getSize (package:naver_map_plugin/src/controller.dart:153:39)

[getSize](https://github.com/LBSTECH/naver_map_plugin/blob/1811e722d44abdd2b92e5721fe284e5b2945c8df/lib/src/controller.dart#L153) 에서 size는 double을 받는데 int 로 고정되어있어 에러가 발생합니다.

특이한 점이 Android에서는 정상작동해서 iOS에서만 임시로 패키지 캐시파일을 수정해 사용중인데 확인 부탁드립니다.

==추가==
[getSize in iOS](https://github.com/LBSTECH/naver_map_plugin/blob/1811e722d44abdd2b92e5721fe284e5b2945c8df/ios/Classes/src/NaverMapController.swift#L124) `mapView.mapWidth`을 float으로 캐스팅

[getSize in android](https://github.com/LBSTECH/naver_map_plugin/blob/1811e722d44abdd2b92e5721fe284e5b2945c8df/android/src/main/java/map/naver/plugin/net/lbstech/naver_map_plugin/NaverMapController.java#L230)` naverMap.getWidth()`을 Integer로 캐스팅

**Comment by sjpark-lbstech** [comment]
## 0.8.7
- LocationOverlay Class 추가.
    - 위치 오버레이 : 사용자의 위치를 표시하기 위해 사용되는 오버레이
    - setPosition : LatLng 객체를 전달하여 특정 위치로 위치 오버레이 이동
    - setBearing : double 형으로 특정 방위각을 전달하여 위치오버레이의 방위각 조정(0은 정북쪽을 의미)
- NaverMapController 의 getSize() type 변환에러 해결
