### ISSUE TITLE
pub.dev에 다른 계정으로 배포를 하지 않으시는 이유가 있나요?

### ISSUE THREAD

**Issue by xpwmaosldk** [LBSTECH/naver_map_plugin#60]
안녕하세요!
`원작자 부재로 [pub.dev](https://pub.dev/packages/naver_map_plugin) 업데이트를 못하고 있습니다.`
라고 하셨는데 새로운 공식 계정으로 옮길 계획은 없으신가요?

**Comment by note11g** [comment]
저도 같은 생각입니다..ㅠㅠ
혹여나 관리가 힘드시다면 제가 이어받아서 관리해도 될지 여부도 궁금합니다..!

**Comment by note11g** [comment]
https://pub.dev/packages/flutter_naver_map
LBSTECH측에 연락드려 허락받고 새로운 패키지 생성했습니다!

@xpwmaosldk

**Comment by Koobonik** [comment]
응원 합니다. 이부분이 걸렸었네요.
다음에 한번 써봐야겠네요 :)
