### ISSUE TITLE
The problem occurs where the example code in the folder is loaded as it is, and I am wondering why.

### ISSUE THREAD

**Issue by Majang9711** [LBSTECH/naver_map_plugin#7]
개발자님의 폴더에 있는 예제 폴더를 그대로 가져와서 테스트를 해보는데 모든 파일에서 오류가 발생합니다.

**Comment by sjpark-lbstech** [comment]
#### Please leave the error message and log of ```flutter doctor``` . if possible, add any other data that indicating a clear situation. even if error got well-known clear reason.

에러 메세지를 같이 남겨주세요. 상황을 알면 답변해드리기가 수월할 것 같습니다. 로그, 스크린샷등 파악할 수 있는 정보를 남겨주세요

**Comment by sjpark-lbstech** [comment]
장시간 응답이 없는 관계로 이슈를 닫습니다.
이후 응답하시면 그때 다시 답변하겠습니다
