### ISSUE TITLE
onCameraChange not work on IOS

### ISSUE THREAD

**Issue by nguyenxuankiet262** [LBSTECH/naver_map_plugin#8]
I can't print the coordinate on IOS but still work on Android.
void _onCameraChange(naver.LatLng latLng) {
    print('Coordinate. (위치 : ${latLng.latitude}, ${latLng.longitude})');
    latitude = latLng.latitude;
    longitude = latLng.longitude;
  }

**Comment by sjpark-lbstech** [comment]
new version-0.8.8 just published to [pub.dev](https://pub.dev/packages/naver_map_plugin) 

## 0.8.8
- fix Error!
    - onCameraChange not work on IOS

it only responds to implicit movement(by calling ```moveCamera()``` directly or additional animation after user's fast drag motion) that I implemented callback in previous version in iOS, which never responds to user's gesture. So, I made it right in 0.8.8 version
