### ISSUE TITLE
지도의 포지션 이동

### ISSUE THREAD

**Issue by BillyoDev** [LBSTECH/naver_map_plugin#9]
카메라의 초기 위치값을 설정 한뒤 변경된 lat, lng 을 지정을 해줘도
카메라의 위치를 변경 할 수 없습니다.

터치를 제외한 카메라의 위치를 변경 할 수 있는 방법이 있습니까?

**Comment by sjpark-lbstech** [comment]
```NaverMap``` 생성시 ```initialCameraPosition``` 속성에 변수처리하여 해당 변수를 바꾸어도 위치는 변경되지 않습니다. 
동적으로 카메라의 위치를 바꾸고 싶으시다면 ```onMapCreated```의 파라미터로 들어오는 ```NaverMapController```의 ```moveCamera()```를 이용해서 위치를 변경할 수 있습니다.  

## NaverMapController 
### instance method

|return value|method name|parameter|
|----|--------|------|
|Future<void>|moveCamera|CameraUpdate|

## CameraUpdate
### static method

- ___scrollTo___
  - 지정된 ```LatLng```으로 카메를 움직입니다.
- ___toCameraPosition___
  - 지정된 ```CameraPosition```으로 카메라를 움직입니다.
- ___zoomIn___
  - 줌을 1만큼 확대합니다
- ___zoomOut___
  - 줌을 1만큼 축소합니다
- ___zoomTo___
  - 지정된 수치로 줌을 변경합니다
- ___fitBounds___
  - 지정된 ```LatLngBounds``` 로 카메라를 이동합니다.

**Comment by Billyo-dev** [comment]
충분한 도움이 되었습니다. 
감사합니다!!
